load dataset

In [1]:
import pandas as pd

file_path = "/content/drive/MyDrive/UseCase - Airlines.xlsx"

excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)

['flights', 'payments', 'bookings', 'passengers']

In [2]:
# Load all datasets from the Excel workbook

flights = pd.read_excel(file_path, sheet_name="flights")
bookings = pd.read_excel(file_path, sheet_name="bookings")
passengers = pd.read_excel(file_path, sheet_name="passengers")
payments = pd.read_excel(file_path, sheet_name="payments")

print("All datasets loaded successfully!")

All datasets loaded successfully!

Finding shape

In [3]:
print("Flights:", flights.shape)
print("Bookings:", bookings.shape)
print("Passengers:", passengers.shape)
print("Payments:", payments.shape)

Flights: (1020, 7)
Bookings: (1000, 9)
Passengers: (1039, 9)
Payments: (1000, 4)

TO find head()

In [4]:
flights.head()

,flight_id,airline,source,destination,departure_time,arrival_time,duration
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00

In [5]:
bookings.head()

,booking_id,passenger_id,flight_id,booking_date,status,passport_number,seat_number,emergency_contact_name,emergency_contact_phone
0,B1000,P1591,AI192,2025-06-14 11:37:36.951,CANCELLED,P1945887,3D,Isaac Bakshi,+91-6478475128
1,B1001,P1803,6F026,2025-11-02 11:37:36.951,CANCELLED,L3482012,18A,Anvi Konda,+91-6647078662
2,B1002,P1083,SJ010,2025-08-25 11:37:36.951,CANCELLED,G8507659,30C,Udant Dewan,+91-8405938220
3,B1003,P1364,AI069,2025-12-30 11:37:36.951,CONFIRMED,M0891776,33A,Harsh Chahal,+91-6264636839
4,B1004,P1885,UK003,2025-10-02 11:37:36.951,PENDING,N5742231,25C,Pahal Balay,+91-9336478266

In [6]:
passengers.head()

,passenger_id,first_name,last_name,age,gender,email,phone,aadhaar_id,date_of_birth
0,P1000,Vivaan,Chatterjee,52,F,vivaan.chatterjee@gmail.com,+91-6896233790,433218196001,1974-04-08
1,P1001,Krishna,Reddy,15,M,krishna.reddy@hotmail.com,+91-6702632297,386379402654,2011-03-07
2,P1002,Myra,Naidu,72,M,myra.naidu@outlook.com,+91-6199585092,615594078161,1954-09-10
3,P1003,Myra,Mishra,61,F,myra.mishra@hotmail.com,+91-8719927151,310341316475,1965-03-12
4,P1004,Saanvi,Banerjee,21,M,saanvi.banerjee@outlook.com,+91-7819595113,419283276483,2005-11-11

In [7]:
payments.head()

  payment_id booking_id    amount payment_method
0    PAY1000      B1116   9883.49     NETBANKING
1    PAY1001      B1738   8457.96     NETBANKING
2    PAY1002      B1873   6495.37            UPI
3    PAY1003      B1914   5079.38     NETBANKING
4    PAY1004      B1967  12518.31           CARD

TO check column names

In [ ]:
print("Flights:", flights.columns.tolist())
print("Bookings:", bookings.columns.tolist())
print("Passengers:", passengers.columns.tolist())
print("Payments:", payments.columns.tolist())

Flights: ['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration']
Bookings: ['booking_id', 'passenger_id', 'flight_id', 'booking_date', 'status', 'passport_number', 'seat_number', 'emergency_contact_name', 'emergency_contact_phone']
Passengers: ['passenger_id', 'first_name', 'last_name', 'age', 'gender', 'email', 'phone', 'aadhaar_id', 'date_of_birth']
Payments: ['payment_id', 'booking_id', 'amount', 'payment_method']

TO check the data types

In [ ]:
print(flights.dtypes)

flight_id                 object
airline                   object
source                    object
destination               object
departure_time    datetime64[ns]
arrival_time      datetime64[ns]
duration                  object
dtype: object

In [ ]:
print(bookings.dtypes)

booking_id                         object
passenger_id                       object
flight_id                          object
booking_date               datetime64[ns]
status                             object
passport_number                    object
seat_number                        object
emergency_contact_name             object
emergency_contact_phone            object
dtype: object

In [ ]:
print(passengers.dtypes)

passenger_id             object
first_name               object
last_name                object
age                       int64
gender                   object
email                    object
phone                    object
aadhaar_id                int64
date_of_birth    datetime64[ns]
dtype: object

In [ ]:
print(payments.dtypes)

payment_id        object
booking_id        object
amount            object
payment_method    object
dtype: object

checking missing values

In [ ]:
flights.isnull().sum()

flight_id          0
airline           41
source             0
destination        0
departure_time     0
arrival_time       0
duration           0
dtype: int64

In [ ]:
bookings.isnull().sum()

booking_id                  0
passenger_id                0
flight_id                   0
booking_date                0
status                     45
passport_number             0
seat_number                 0
emergency_contact_name      0
emergency_contact_phone     0
dtype: int64

In [ ]:
passengers.isnull().sum()

passenger_id      0
first_name        0
last_name        10
age               0
gender            0
email             0
phone             0
aadhaar_id        0
date_of_birth     0
dtype: int64

In [ ]:
payments.isnull().sum()

payment_id         0
booking_id         0
amount            48
payment_method     0
dtype: int64

**To check duplicate rows**

In [ ]:
print("Flight duplicates:", flights.duplicated().sum())
print("Booking duplicates:", bookings.duplicated().sum())
print("Passenger duplicates:", passengers.duplicated().sum())
print("Payment duplicates:", payments.duplicated().sum())

Flight duplicates: 15
Booking duplicates: 0
Passenger duplicates: 0
Payment duplicates: 0

 pandas simple info() function

In [ ]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   flight_id       1020 non-null   object
 1   airline         979 non-null    object
 2   source          1020 non-null   object
 3   destination     1020 non-null   object
 4   departure_time  1020 non-null   datetime64[ns]
 5   arrival_time    1020 non-null   datetime64[ns]
 6   duration        1020 non-null   object
dtypes: datetime64[ns](2), object(5)
memory usage: 55.9+ KB

In [ ]:
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   booking_id               1000 non-null   object
 1   passenger_id             1000 non-null   object
 2   flight_id                1000 non-null   object
 3   booking_date             1000 non-null   datetime64[ns]
 4   status                   955 non-null    object
 5   passport_number          1000 non-null   object
 6   seat_number              1000 non-null   object
 7   emergency_contact_name   1000 non-null   object
 8   emergency_contact_phone  1000 non-null   object
dtypes: datetime64[ns](1), object(8)
memory usage: 70.4+ KB

In [ ]:
passengers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   passenger_id   1039 non-null   object
 1   first_name     1039 non-null   object
 2   last_name      1029 non-null   object
 3   age            1039 non-null   int64
 4   gender         1039 non-null   object
 5   email          1039 non-null   object
 6   phone          1039 non-null   object
 7   aadhaar_id     1039 non-null   int64
 8   date_of_birth  1039 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 73.2+ KB

In [ ]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      1000 non-null   object
 1   booking_id      1000 non-null   object
 2   amount          952 non-null    object
 3   payment_method  1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

TO check flight ID

In [ ]:
flights["flight_id"].head(20)

0     SJ010
1     AI155
2     UK094
3     AI245
4     AI192
5     SJ158
6     6F196
7     AI080
8     6F025
9     6F251
10    AI137
11    6F026
12    UK167
13    UK027
14    AI069
15    AI058
16    AI140
17    SJ239
18    6F099
19    AI048
Name: flight_id, dtype: object

TO count  unique flight Ids

In [ ]:
print("Total rows:", len(flights))
print("Unique flight IDs:", flights["flight_id"].nunique())

Total rows: 1020
Unique flight IDs: 1004

Check missing flight IDs

In [ ]:
print("Missing flight IDs:", flights["flight_id"].isnull().sum())

Missing flight IDs: 0

TO check the airline values

In [ ]:
print(flights["airline"].value_counts(dropna=False))

airline
IndiGo       249
SpiceJet     240
Air India    236
Vistara      223
NaN           41
UNKNOWN       31
Name: count, dtype: int64

check source and destination

In [ ]:
print("Source cities:")
print(flights["source"].value_counts(dropna=False))

print("\nDestination cities:")
print(flights["destination"].value_counts(dropna=False))

Source cities:
source
BOM    207
HYD    180
CCU    174
DEL    163
MAA    157
BLR    139
Name: count, dtype: int64

Destination cities:
destination
DEL    200
CCU    188
BOM    174
BLR    165
MAA    151
HYD    142
Name: count, dtype: int64

Investigate time colums

In [ ]:
flights[["departure_time", "arrival_time"]].head(10)

           departure_time            arrival_time
0 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701
1 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703
2 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702
3 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704
4 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703
5 2026-04-20 23:05:41.703 2026-04-21 01:24:41.703
6 2026-04-20 23:04:41.703 2026-04-21 00:47:41.703
7 2026-04-20 23:03:41.702 2026-04-21 00:35:41.702
8 2026-04-20 23:02:41.701 2026-04-20 23:57:41.701
9 2026-04-20 22:56:41.703 2026-04-20 23:37:41.703

to check datatype of flights

In [ ]:
print(flights["departure_time"].dtype)
print(flights["arrival_time"].dtype)

datetime64[ns]
datetime64[ns]

In [ ]:
flights["duration"].head(10)

0    02:54:00
1    01:48:00
2    01:45:00
3    02:36:00
4    04:59:00
5    02:19:00
6    01:43:00
7    01:32:00
8    00:55:00
9    00:41:00
Name: duration, dtype: object

check the duration column

In [ ]:
flights["duration"].head(10)

0    02:54:00
1    01:48:00
2    01:45:00
3    02:36:00
4    04:59:00
5    02:19:00
6    01:43:00
7    01:32:00
8    00:55:00
9    00:41:00
Name: duration, dtype: object

In [ ]:
print(flights["duration"].dtype)

object

check for overnight flights

In [ ]:
flights["departure_time"] = pd.to_datetime(flights["departure_time"])
flights["arrival_time"] = pd.to_datetime(flights["arrival_time"])

In [ ]:
overnight = flights["arrival_time"].dt.date > flights["departure_time"].dt.date

print("Overnight flights:", overnight.sum())

Overnight flights: 124

In [ ]:
flights[overnight][
    ["flight_id", "source", "destination",
     "departure_time", "arrival_time"]
].head(10)

,flight_id,source,destination,departure_time,arrival_time
0,SJ010,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701
1,AI155,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703
2,UK094,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702
3,AI245,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704
4,AI192,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703
5,SJ158,DEL,HYD,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703
6,6F196,CCU,MAA,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703
7,AI080,BOM,HYD,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702
10,AI137,BOM,DEL,2026-04-20 22:49:41.702,2026-04-21 01:17:41.702
11,6F026,BOM,CCU,2026-04-20 22:46:42.000,2026-04-21 03:13:42.000

Flight clean

In [ ]:
clean_flights = flights.copy()

print("Clean flights table created.")

Clean flights table created.

In [ ]:
clean_flights.head()

,flight_id,airline,source,destination,departure_time,arrival_time,duration
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00

In [ ]:
print("Before:", len(clean_flights))

clean_flights = clean_flights.drop_duplicates()

print("After:", len(clean_flights))

Before: 1020
After: 1005

In [ ]:
clean_flights.isnull().sum()

flight_id          0
airline           39
source             0
destination        0
departure_time     0
arrival_time       0
duration           0
dtype: int64

view the rows with missing airlines

In [ ]:
clean_flights[clean_flights["airline"].isnull()]

,flight_id,airline,source,destination,departure_time,arrival_time,duration
57,UK209,NaN,MAA,BLR,2026-04-20 19:02:41.704,2026-04-20 21:47:41.704,02:45:00
63,6F270,NaN,HYD,MAA,2026-04-20 18:14:41.701,2026-04-20 19:02:41.701,00:48:00
89,UK224,NaN,CCU,MAA,2026-04-20 16:25:41.704,2026-04-20 20:24:41.704,03:59:00
118,6F261,NaN,CCU,DEL,2026-04-20 14:31:41.703,2026-04-20 17:29:41.703,02:58:00
120,6F254,NaN,MAA,BLR,2026-04-20 14:26:41.703,2026-04-20 18:01:41.703,03:35:00
124,6F259,NaN,BOM,DEL,2026-04-20 14:10:41.703,2026-04-20 15:21:41.703,01:11:00
133,UK141,NaN,HYD,MAA,2026-04-20 13:38:41.703,2026-04-20 15:59:41.703,02:21:00
150,6F255,NaN,DEL,BOM,2026-04-20 11:59:41.703,2026-04-20 15:33:41.703,03:34:00
218,AI047,NaN,CCU,MAA,2026-04-20 06:36:41.701,2026-04-20 07:23:41.701,00:47:00
222,AI128,NaN,BOM,CCU,2026-04-20 06:07:41.702,2026-04-20 10:03:41.702,03:56:00
225,SJ138,NaN,BLR,BOM,2026-04-20 05:55:41.702,2026-04-20 06:43:41.702,00:48:00
279,AI009,NaN,DEL,CCU,2026-04-20 01:31:41.701,2026-04-20 04:05:41.701,02:34:00
284,AI226,NaN,BLR,HYD,2026-04-20 01:19:41.703,2026-04-20 04:08:41.703,02:49:00
299,6F272,NaN,HYD,MAA,2026-04-19 23:35:41.702,2026-04-20 00:22:41.702,00:47:00
314,SJ099,NaN,MAA,BLR,2026-04-19 22:14:41.702,2026-04-20 00:34:41.702,02:20:00
319,6F260,NaN,CCU,DEL,2026-04-19 21:51:41.702,2026-04-20 01:14:41.702,03:23:00
351,6F271,NaN,HYD,MAA,2026-04-19 19:33:41.702,2026-04-19 22:52:41.702,03:19:00
357,6F256,NaN,BOM,CCU,2026-04-19 18:40:41.702,2026-04-19 19:13:41.702,00:33:00
376,AI252,NaN,HYD,DEL,2026-04-19 17:30:41.704,2026-04-19 21:54:41.704,04:24:00
395,SJ203,NaN,DEL,HYD,2026-04-19 16:22:41.703,2026-04-19 18:27:41.703,02:05:00
398,AI168,NaN,DEL,CCU,2026-04-19 15:50:41.703,2026-04-19 20:20:41.703,04:30:00
461,AI037,NaN,BOM,BLR,2026-04-19 11:14:41.701,2026-04-19 15:13:41.701,03:59:00
482,AI219,NaN,BLR,DEL,2026-04-19 09:28:41.703,2026-04-19 11:27:41.703,01:59:00
492,SJ051,NaN,BOM,BLR,2026-04-19 08:40:41.701,2026-04-19 12:18:41.701,03:38:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
562,AI243,NaN,BLR,BOM,2026-04-19 02:50:41.704,2026-04-19 05:09:41.704,02:19:00
630,UK081,NaN,BLR,DEL,2026-04-18 22:00:41.702,2026-04-18 23:00:41.702,01:00:00
658,UK088,NaN,MAA,BLR,2026-04-18 19:16:41.702,2026-04-18 23:36:41.702,04:20:00
664,SJ225,NaN,DEL,HYD,2026-04-18 18:16:41.704,2026-04-18 20:53:41.704,02:37:00
719,6F264,NaN,DEL,HYD,2026-04-18 14:03:41.701,2026-04-18 18:23:41.701,04:20:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
774,UK151,NaN,BOM,CCU,2026-04-18 10:11:41.703,2026-04-18 13:30:41.703,03:19:00
858,6F265,NaN,DEL,HYD,2026-04-18 02:27:41.703,2026-04-18 03:24:41.703,00:57:00
870,AI125,NaN,CCU,DEL,2026-04-18 01:12:41.702,2026-04-18 04:51:41.702,03:39:00
873,UK043,NaN,DEL,HYD,2026-04-18 00:48:41.701,2026-04-18 04:52:41.701,04:04:00
880,AI065,NaN,MAA,BLR,2026-04-18 00:09:41.701,2026-04-18 05:00:41.701,04:51:00
924,AI230,NaN,CCU,BLR,2026-04-17 20:37:41.704,2026-04-18 00:22:41.704,03:45:00
925,6F268,NaN,DEL,MAA,2026-04-17 20:29:41.701,2026-04-17 21:58:41.701,01:29:00
956,AI145,NaN,DEL,BOM,2026-04-17 17:06:41.702,2026-04-17 21:31:41.702,04:25:00

In [ ]:
clean_flights.loc[
    clean_flights["airline"].isnull(),
    ["flight_id", "source", "destination"]
]

    flight_id source destination
57      UK209    MAA         BLR
63      6F270    HYD         MAA
89      UK224    CCU         MAA
118     6F261    CCU         DEL
120     6F254    MAA         BLR
124     6F259    BOM         DEL
133     UK141    HYD         MAA
150     6F255    DEL         BOM
218     AI047    CCU         MAA
222     AI128    BOM         CCU
225     SJ138    BLR         BOM
279     AI009    DEL         CCU
284     AI226    BLR         HYD
299     6F272    HYD         MAA
314     SJ099    MAA         BLR
319     6F260    CCU         DEL
351     6F271    HYD         MAA
357     6F256    BOM         CCU
376     AI252    HYD         DEL
395     SJ203    DEL         HYD
398     AI168    DEL         CCU
461     AI037    BOM         BLR
482     AI219    BLR         DEL
492     SJ051    BOM         BLR
549     AI020    BOM         BLR
562     AI243    BLR         BOM
630     UK081    BLR         DEL
658     UK088    MAA         BLR
664     SJ225    DEL         HYD
719     6F264    DEL         HYD
758     UK139    BLR         MAA
774     UK151    BOM         CCU
858     6F265    DEL         HYD
870     AI125    CCU         DEL
873     UK043    DEL         HYD
880     AI065    MAA         BLR
924     AI230    CCU         BLR
925     6F268    DEL         MAA
956     AI145    DEL         BOM

In [ ]:
clean_flights[["flight_id", "airline"]].dropna().head(20)

   flight_id    airline
0      SJ010   SpiceJet
1      AI155  Air India
2      UK094    Vistara
3      AI245  Air India
4      AI192  Air India
5      SJ158   SpiceJet
6      6F196     IndiGo
7      AI080  Air India
8      6F025     IndiGo
9      6F251    UNKNOWN
10     AI137  Air India
11     6F026     IndiGo
12     UK167    Vistara
13     UK027    Vistara
14     AI069    UNKNOWN
15     AI058  Air India
16     AI140  Air India
17     SJ239   SpiceJet
18     6F099     IndiGo
19     AI048  Air India

In [ ]:
clean_flights["prefix"] = clean_flights["flight_id"].astype(str).str[:2]

clean_flights.groupby("prefix")["airline"].unique()

prefix
6F       [IndiGo, UNKNOWN, nan]
AI    [Air India, UNKNOWN, nan]
SJ     [SpiceJet, UNKNOWN, nan]
UK      [Vistara, UNKNOWN, nan]
Name: airline, dtype: object

In [ ]:
airline_map = {
    "6F": "IndiGo",
    "AI": "Air India",
    "SJ": "SpiceJet",
    "UK": "Vistara"
}

clean_flights["airline"] = clean_flights["airline"].fillna(
    clean_flights["prefix"].map(airline_map)
)

In [ ]:
clean_flights["airline"].isnull().sum()

np.int64(0)

In [ ]:
clean_flights["airline"].value_counts(dropna=False)

airline
IndiGo       261
Air India    247
SpiceJet     241
Vistara      226
UNKNOWN       30
Name: count, dtype: int64

Investigate unknown records

In [ ]:
clean_flights[clean_flights["airline"] == "UNKNOWN"][
    ["flight_id", "source", "destination"]
]

    flight_id source destination
9       6F251    DEL         BLR
14      AI069    DEL         BOM
28      UK003    HYD         DEL
58      SJ043    MAA         DEL
83      AI242    BLR         CCU
90      UK077    HYD         BOM
148     AI222    BOM         DEL
189     AI044    MAA         BLR
209     UK229    HYD         DEL
220     AI088    MAA         DEL
253     6F250    DEL         BLR
270     6F250    CCU         BLR
304     SJ029    HYD         DEL
394     6F253    MAA         BLR
418     AI100    CCU         BOM
443     SJ027    BOM         MAA
507     6F263    DEL         HYD
533     AI046    DEL         BOM
578     6F262    MAA         DEL
580     6F269    HYD         MAA
640     AI250    BOM         CCU
677     UK112    CCU         DEL
693     6F257    MAA         CCU
709     6F252    MAA         BLR
765     SJ140    HYD         DEL
768     SJ096    DEL         HYD
780     6F266    CCU         MAA
794     6F267    DEL         MAA
933     SJ212    MAA         BLR
996     6F258    BOM         DEL

In [ ]:
clean_flights[clean_flights["airline"] == "UNKNOWN"]["prefix"].value_counts()

prefix
6F    12
AI     8
SJ     6
UK     4
Name: count, dtype: int64

In [ ]:
clean_flights["airline"] = clean_flights["airline"].replace(
    "UNKNOWN", None
)

clean_flights["airline"] = clean_flights["airline"].fillna(
    clean_flights["prefix"].map(airline_map)
)

In [ ]:
print(clean_flights["airline"].isnull().sum())

0

In [ ]:
print(clean_flights["airline"].value_counts())

airline
IndiGo       273
Air India    255
SpiceJet     247
Vistara      230
Name: count, dtype: int64

In [ ]:
clean_flights["airline"] = clean_flights["airline"].replace("UNKNOWN", None)

clean_flights["airline"] = clean_flights["airline"].fillna(
    clean_flights["prefix"].map(airline_map)
)

print("Missing airline values:", clean_flights["airline"].isnull().sum())

Missing airline values: 0

Check all prefixes

In [ ]:
print(clean_flights["prefix"].value_counts(dropna=False))

prefix
6F    273
AI    255
SJ    247
UK    230
Name: count, dtype: int64

In [ ]:
pattern = r"^(6F|AI|SJ|UK)\d{3}$"

valid_ids = clean_flights["flight_id"].astype(str).str.match(pattern)

print("Valid flight IDs:", valid_ids.sum())
print("Invalid flight IDs:", (~valid_ids).sum())

Valid flight IDs: 1005
Invalid flight IDs: 0

to check the invalid ids

In [ ]:
clean_flights.loc[~valid_ids, ["flight_id", "airline"]]

Empty DataFrame
Columns: [flight_id, airline]
Index: []

Check for missing times

In [ ]:
print("Missing departure time:", clean_flights["departure_time"].isnull().sum())
print("Missing arrival time:", clean_flights["arrival_time"].isnull().sum())

Missing departure time: 0
Missing arrival time: 0

In [ ]:
print("Earliest departure:", clean_flights["departure_time"].min())
print("Latest departure:", clean_flights["departure_time"].max())

print("Earliest arrival:", clean_flights["arrival_time"].min())
print("Latest arrival:", clean_flights["arrival_time"].max())

Earliest departure: 2026-04-17 12:25:41.701000
Latest departure: 2026-04-20 23:38:41.701000
Earliest arrival: 2026-04-17 14:10:41.703000
Latest arrival: 2026-04-21 04:04:41.703000

In [ ]:
overnight = clean_flights["arrival_time"].dt.date > clean_flights["departure_time"].dt.date

print("Overnight flights:", overnight.sum())

Overnight flights: 122

In [ ]:
clean_flights.loc[
    overnight,
    ["flight_id", "source", "destination", "departure_time", "arrival_time"]
].head(10)

,flight_id,source,destination,departure_time,arrival_time
0,SJ010,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701
1,AI155,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703
2,UK094,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702
3,AI245,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704
4,AI192,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703
5,SJ158,DEL,HYD,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703
6,6F196,CCU,MAA,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703
7,AI080,BOM,HYD,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702
10,AI137,BOM,DEL,2026-04-20 22:49:41.702,2026-04-21 01:17:41.702
11,6F026,BOM,CCU,2026-04-20 22:46:42.000,2026-04-21 03:13:42.000

Calculate the correct flight duration

In [ ]:
clean_flights["calculated_duration"] = (
    clean_flights["arrival_time"] - clean_flights["departure_time"]
)

In [ ]:
clean_flights[
    ["flight_id", "departure_time", "arrival_time", "calculated_duration"]
].head(10)

,flight_id,departure_time,arrival_time,calculated_duration
0,SJ010,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,0 days 02:54:00
1,AI155,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,0 days 01:48:00
2,UK094,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,0 days 01:45:00
3,AI245,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,0 days 02:36:00
4,AI192,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,0 days 04:59:00
5,SJ158,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703,0 days 02:19:00
6,6F196,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703,0 days 01:43:00
7,AI080,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702,0 days 01:32:00
8,6F025,2026-04-20 23:02:41.701,2026-04-20 23:57:41.701,0 days 00:55:00
9,6F251,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,0 days 00:41:00

Convert duration into minutes

In [ ]:

clean_flights["duration_minutes"] = (
    clean_flights["calculated_duration"].dt.total_seconds() / 60
)

In [ ]:
clean_flights[
    ["flight_id", "calculated_duration", "duration_minutes"]
].head(10)

  flight_id calculated_duration  duration_minutes
0     SJ010     0 days 02:54:00             174.0
1     AI155     0 days 01:48:00             108.0
2     UK094     0 days 01:45:00             105.0
3     AI245     0 days 02:36:00             156.0
4     AI192     0 days 04:59:00             299.0
5     SJ158     0 days 02:19:00             139.0
6     6F196     0 days 01:43:00             103.0
7     AI080     0 days 01:32:00              92.0
8     6F025     0 days 00:55:00              55.0
9     6F251     0 days 00:41:00              41.0

— Compare original vs calculated duration

In [ ]:
clean_flights[
    ["flight_id", "duration", "calculated_duration", "duration_minutes"]
].head(20)

   flight_id  duration calculated_duration  duration_minutes
0      SJ010  02:54:00     0 days 02:54:00             174.0
1      AI155  01:48:00     0 days 01:48:00             108.0
2      UK094  01:45:00     0 days 01:45:00             105.0
3      AI245  02:36:00     0 days 02:36:00             156.0
4      AI192  04:59:00     0 days 04:59:00             299.0
5      SJ158  02:19:00     0 days 02:19:00             139.0
6      6F196  01:43:00     0 days 01:43:00             103.0
7      AI080  01:32:00     0 days 01:32:00              92.0
8      6F025  00:55:00     0 days 00:55:00              55.0
9      6F251  00:41:00     0 days 00:41:00              41.0
10     AI137  02:28:00     0 days 02:28:00             148.0
11     6F026  04:27:00     0 days 04:27:00             267.0
12     UK167  03:01:00     0 days 03:01:00             181.0
13     UK027  02:21:00     0 days 02:21:00             141.0
14     AI069  03:46:00     0 days 03:46:00             226.0
15     AI058  01:38:00     0 days 01:38:00              98.0
16     AI140  03:43:00     0 days 03:43:00             223.0
17     SJ239  01:46:00     0 days 01:46:00             106.0
18     6F099  00:35:00     0 days 00:35:00              35.0
19     AI048  03:52:00     0 days 03:52:00             232.0

In [ ]:
def time_to_minutes(value):
    return value.hour * 60 + value.minute + value.second / 60

clean_flights["original_minutes"] = clean_flights["duration"].apply(
    time_to_minutes
)

print("Original duration converted to minutes.")

Original duration converted to minutes.

In [ ]:
clean_flights[
    ["flight_id", "duration", "original_minutes", "duration_minutes"]
].head(10)

  flight_id  duration  original_minutes  duration_minutes
0     SJ010  02:54:00             174.0             174.0
1     AI155  01:48:00             108.0             108.0
2     UK094  01:45:00             105.0             105.0
3     AI245  02:36:00             156.0             156.0
4     AI192  04:59:00             299.0             299.0
5     SJ158  02:19:00             139.0             139.0
6     6F196  01:43:00             103.0             103.0
7     AI080  01:32:00              92.0              92.0
8     6F025  00:55:00              55.0              55.0
9     6F251  00:41:00              41.0              41.0

In [ ]:
clean_flights["duration_difference"] = (
    clean_flights["duration_minutes"]
    - clean_flights["original_minutes"]
)

print(clean_flights["duration_difference"].describe())

count    1005.000000
mean       -1.432702
std        45.423386
min     -1440.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         0.004983
Name: duration_difference, dtype: float64

In [ ]:
print(
    "Duration mismatches:",
    (clean_flights["duration_difference"] != 0).sum()
)

Duration mismatches: 28

In [ ]:
clean_flights[
    ["flight_id", "duration", "calculated_duration",
     "original_minutes", "duration_difference"]
].loc[
    clean_flights["duration_difference"] != 0
].sort_values(
    "duration_difference",
    key=abs,
    ascending=False
).head(10)

,flight_id,duration,calculated_duration,original_minutes,duration_difference
355,SJ192,1899-12-29 05:00:00,-1 days +05:00:00,300.0,-1440.000000
928,SJ035,01:00:00.299000,0 days 01:00:00.299000,60.0,0.004983
546,AI007,02:00:00.299000,0 days 02:00:00.299000,120.0,0.004983
501,AI032,02:00:00.299000,0 days 02:00:00.299000,120.0,0.004983
764,AI008,02:00:00.299000,0 days 02:00:00.299000,120.0,0.004983
850,6F006,02:00:00.299000,0 days 02:00:00.299000,120.0,0.004983
976,6F011,02:00:00.299000,0 days 02:00:00.299000,120.0,0.004983
822,6F060,02:00:00.299000,0 days 02:00:00.299000,120.0,0.004983
853,UK072,03:00:00.298000,0 days 03:00:00.298000,180.0,0.004967
715,6F107,03:00:00.298000,0 days 03:00:00.298000,180.0,0.004967

In [ ]:
import datetime

def time_to_minutes(value):
    if isinstance(value, datetime.datetime):
        return value.hour * 60 + value.minute + value.second / 60 + value.microsecond / 60000000

    if isinstance(value, datetime.time):
        return value.hour * 60 + value.minute + value.second / 60 + value.microsecond / 60000000

    return None


clean_flights["original_minutes"] = clean_flights["duration"].apply(time_to_minutes)

In [ ]:
clean_flights["duration_difference"] = (
    clean_flights["duration_minutes"]
    - clean_flights["original_minutes"]
)

print(
    "Duration mismatches:",
    (clean_flights["duration_difference"].abs() > 0.01).sum()
)

Duration mismatches: 1

In [ ]:
clean_flights[
    clean_flights["duration_difference"].abs() > 0.01
][
    ["flight_id", "duration", "departure_time",
     "arrival_time", "duration_minutes",
     "original_minutes", "duration_difference"]
]

,flight_id,duration,departure_time,arrival_time,duration_minutes,original_minutes,duration_difference
355,SJ192,1899-12-29 05:00:00,2026-04-19 18:45:42,2026-04-18 23:45:42,-1140.0,300.0,-1440.0

In [ ]:
clean_flights.loc[
    clean_flights["flight_id"] == "SJ192",
    "arrival_time"
] = (
    clean_flights.loc[
        clean_flights["flight_id"] == "SJ192",
        "departure_time"
    ]
    + pd.Timedelta(hours=5)
)

In [ ]:
clean_flights["calculated_duration"] = (
    clean_flights["arrival_time"]
    - clean_flights["departure_time"]
)

clean_flights["duration_minutes"] = (
    clean_flights["calculated_duration"].dt.total_seconds() / 60
)

In [ ]:
clean_flights[
    clean_flights["flight_id"] == "SJ192"
][
    ["flight_id", "departure_time", "arrival_time",
     "duration_minutes", "original_minutes"]
]

,flight_id,departure_time,arrival_time,duration_minutes,original_minutes
355,SJ192,2026-04-19 18:45:42,2026-04-19 23:45:42,300.0,300.0

In [ ]:
clean_flights["is_overnight"] = (
    clean_flights["arrival_time"].dt.date
    > clean_flights["departure_time"].dt.date
)

clean_flights["departure_date"] = (
    clean_flights["departure_time"].dt.date
)

clean_flights["departure_hour"] = (
    clean_flights["departure_time"].dt.hour
)

clean_flights["route"] = (
    clean_flights["source"] + " → " + clean_flights["destination"]
)

clean_flights[
    ["flight_id", "airline", "route", "departure_date",
     "departure_hour", "duration_minutes", "is_overnight"]
].head(10)

,flight_id,airline,route,departure_date,departure_hour,duration_minutes,is_overnight
0,SJ010,SpiceJet,CCU → MAA,2026-04-20,23,174.0,True
1,AI155,Air India,BOM → CCU,2026-04-20,23,108.0,True
2,UK094,Vistara,BOM → CCU,2026-04-20,23,105.0,True
3,AI245,Air India,BOM → CCU,2026-04-20,23,156.0,True
4,AI192,Air India,MAA → BOM,2026-04-20,23,299.0,True
5,SJ158,SpiceJet,DEL → HYD,2026-04-20,23,139.0,True
6,6F196,IndiGo,CCU → MAA,2026-04-20,23,103.0,True
7,AI080,Air India,BOM → HYD,2026-04-20,23,92.0,True
8,6F025,IndiGo,BLR → BOM,2026-04-20,23,55.0,False
9,6F251,IndiGo,DEL → BLR,2026-04-20,22,41.0,False

In [ ]:
clean_flights.isnull().sum()

flight_id              0
airline                0
source                 0
destination            0
departure_time         0
arrival_time           0
duration               0
prefix                 0
calculated_duration    0
duration_minutes       0
original_minutes       0
duration_difference    0
is_overnight           0
departure_date         0
departure_hour         0
route                  0
dtype: int64

In [ ]:
print("Duplicate rows:", clean_flights.duplicated().sum())

Duplicate rows: 0

In [ ]:
temporary_columns = [
    "prefix",
    "calculated_duration",
    "original_minutes",
    "duration_difference"
]

clean_flights = clean_flights.drop(columns=temporary_columns)

print(clean_flights.columns.tolist())

['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration', 'duration_minutes', 'is_overnight', 'departure_date', 'departure_hour', 'route']

check the final structure

In [ ]:
print("Final Flights shape:", clean_flights.shape)
clean_flights.head()

Final Flights shape: (1005, 12)

,flight_id,airline,source,destination,departure_time,arrival_time,duration,duration_minutes,is_overnight,departure_date,departure_hour,route
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00,174.0,True,2026-04-20,23,CCU → MAA
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00,108.0,True,2026-04-20,23,BOM → CCU
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00,105.0,True,2026-04-20,23,BOM → CCU
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00,156.0,True,2026-04-20,23,BOM → CCU
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00,299.0,True,2026-04-20,23,MAA → BOM

## 2. Bookings Data Cleaning

The bookings dataset contains booking information, passenger and flight references, booking status, seat details, and passenger contact information.

A separate copy of the raw bookings data is created so that the original dataset remains unchanged. The clean copy will be used for data quality checks, cleaning, validation, and transformation.

In [ ]:
clean_bookings = bookings.copy()

print("Original rows:", len(bookings))
print("Clean bookings rows:", len(clean_bookings))

Original rows: 1000
Clean bookings rows: 1000

### 2.1 Initial Data Profiling

The bookings dataset is profiled to understand its structure, data types, missing values, and duplicate records before applying any cleaning operations.

In [ ]:
print("Shape:", clean_bookings.shape)
print("\nColumns:")
print(clean_bookings.columns.tolist())

print("\nData types:")
print(clean_bookings.dtypes)

print("\nMissing values:")
print(clean_bookings.isnull().sum())

print("\nDuplicate rows:", clean_bookings.duplicated().sum())

Shape: (1000, 9)

Columns:
['booking_id', 'passenger_id', 'flight_id', 'booking_date', 'status', 'passport_number', 'seat_number', 'emergency_contact_name', 'emergency_contact_phone']

Data types:
booking_id                         object
passenger_id                       object
flight_id                          object
booking_date               datetime64[ns]
status                             object
passport_number                    object
seat_number                        object
emergency_contact_name             object
emergency_contact_phone            object
dtype: object

Missing values:
booking_id                  0
passenger_id                0
flight_id                   0
booking_date                0
status                     45
passport_number             0
seat_number                 0
emergency_contact_name      0
emergency_contact_phone     0
dtype: int64

Duplicate rows: 0

### 2.2 Sample Records

The first few records are examined to understand the values and format of the booking attributes.

In [ ]:
clean_bookings.head(10)

,booking_id,passenger_id,flight_id,booking_date,status,passport_number,seat_number,emergency_contact_name,emergency_contact_phone
0,B1000,P1591,AI192,2025-06-14 11:37:36.951,CANCELLED,P1945887,3D,Isaac Bakshi,+91-6478475128
1,B1001,P1803,6F026,2025-11-02 11:37:36.951,CANCELLED,L3482012,18A,Anvi Konda,+91-6647078662
2,B1002,P1083,SJ010,2025-08-25 11:37:36.951,CANCELLED,G8507659,30C,Udant Dewan,+91-8405938220
3,B1003,P1364,AI069,2025-12-30 11:37:36.951,CONFIRMED,M0891776,33A,Harsh Chahal,+91-6264636839
4,B1004,P1885,UK003,2025-10-02 11:37:36.951,PENDING,N5742231,25C,Pahal Balay,+91-9336478266
5,B1005,P1548,AI048,2025-08-31 11:37:36.951,CONFIRMED,B0402369,13D,Ayushman Chander,+91-7558392726
6,B1006,P1341,AI140,2025-06-29 11:37:36.951,CANCELLED,W9430120,17F,Tejas Kaul,+91-9945047864
7,B1007,P1838,UK167,2026-03-12 11:37:36.951,CONFIRMED,C3727117,22E,Yashasvi Bala,+91-8603505776
8,B1008,P1406,AI245,2025-09-07 11:37:36.951,PENDING,J9885582,34F,Rushil Saini,+91-8965638807
9,B1009,P1424,SJ158,2025-04-28 11:37:36.951,CANCELLED,Y3306745,33C,Thomas Sen,+91-9877686278

2.3 Duplicate Record Removal

In [ ]:
print("Rows before removing duplicates:", len(clean_bookings))

clean_bookings = clean_bookings.drop_duplicates()

print("Rows after removing duplicates:", len(clean_bookings))
print("Duplicates remaining:", clean_bookings.duplicated().sum())

Rows before removing duplicates: 1000
Rows after removing duplicates: 1000
Duplicates remaining: 0

2.4 Missing Value Analysis

In [ ]:
missing_bookings = clean_bookings.isnull().sum()

print("Missing values in each column:")
print(missing_bookings)

Missing values in each column:
booking_id                  0
passenger_id                0
flight_id                   0
booking_date                0
status                     45
passport_number             0
seat_number                 0
emergency_contact_name      0
emergency_contact_phone     0
dtype: int64

2.5 Booking Status Validation

In [ ]:
print("Booking status values:")
print(clean_bookings["status"].value_counts(dropna=False))

Booking status values:
status
CONFIRMED    320
CANCELLED    314
PENDING      291
NaN           45
INVALID       30
Name: count, dtype: int64

Invesrtigation of missing and invalid booking status

In [ ]:
problem_status = clean_bookings[
    clean_bookings["status"].isnull() |
    (clean_bookings["status"] == "INVALID")
]

problem_status[
    [
        "booking_id",
        "passenger_id",
        "flight_id",
        "booking_date",
        "status",
        "seat_number"
    ]
].head(20)

,booking_id,passenger_id,flight_id,booking_date,status,seat_number
15,B1015,P1431,UK094,2025-10-21 11:37:36.951,NaN,6F
33,B1033,P1987,UK026,2025-05-06 11:37:36.951,NaN,19A
45,B1045,P1057,SJ214,2026-03-19 11:37:36.951,NaN,18C
49,B1049,P1072,SJ153,2025-07-28 11:37:36.951,INVALID,3C
97,B1097,P1959,6F017,2025-08-26 11:37:36.951,NaN,34F
98,B1098,P1491,6F245,2025-10-15 11:37:36.951,NaN,13D
102,B1102,P1448,SJ196,2025-10-06 11:37:36.951,INVALID,15F
162,B1162,P1027,AI146,2025-04-22 11:37:36.951,INVALID,32D
198,B1198,P1913,SJ022,2025-06-16 11:37:36.951,INVALID,29A
208,B1208,P1284,SJ052,2025-07-22 11:37:36.951,INVALID,9A
214,B1214,P1187,UK194,2025-08-14 11:37:36.951,NaN,23B
223,B1223,P1755,6F056,2026-04-09 11:37:36.951,NaN,15A
237,B1237,P1754,AI047,2025-11-16 11:37:36.951,NaN,15B
238,B1238,P1296,SJ186,2025-10-20 11:37:36.951,NaN,8E
245,B1245,P1139,6F201,2026-04-17 11:37:36.951,NaN,26A
268,B1268,P1657,AI102,2026-01-16 11:37:36.951,INVALID,12A
270,B1270,P1573,SJ017,2025-06-02 11:37:36.951,NaN,22E
273,B1273,P1892,AI150,2025-06-05 11:37:36.951,NaN,28B
279,B1279,P1631,6F019,2025-05-10 11:37:36.951,NaN,28C
283,B1283,P1860,AI103,2025-05-08 11:37:36.951,INVALID,29D

In [ ]:
# Save current cleaned datasets as checkpoint files

clean_flights.to_csv(
    "/content/drive/MyDrive/clean_flights_checkpoint.csv",
    index=False
)

clean_bookings.to_csv(
    "/content/drive/MyDrive/clean_bookings_checkpoint.csv",
    index=False
)

print("Checkpoint saved successfully!")

Checkpoint saved successfully!

### Clean Status

In [ ]:
clean_bookings["status"] = clean_bookings["status"].replace(
    "INVALID", "UNKNOWN"
)

clean_bookings["status"] = clean_bookings["status"].fillna(
    "UNKNOWN"
)

print(clean_bookings["status"].value_counts())

status
CONFIRMED    320
CANCELLED    314
PENDING      291
UNKNOWN       75
Name: count, dtype: int64

### Check Status

In [ ]:
print("Missing status values:", clean_bookings["status"].isnull().sum())

print(
    "Invalid status values:",
    (clean_bookings["status"] == "INVALID").sum()
)

print("\nFinal status distribution:")
print(clean_bookings["status"].value_counts())

Missing status values: 0
Invalid status values: 0

Final status distribution:
status
CONFIRMED    320
CANCELLED    314
PENDING      291
UNKNOWN       75
Name: count, dtype: int64

### Validate Booking ID

In [ ]:
booking_id_pattern = r"^B\d{4}$"

valid_booking_ids = clean_bookings["booking_id"].astype(str).str.match(
    booking_id_pattern
)

print("Valid booking IDs:", valid_booking_ids.sum())
print("Invalid booking IDs:", (~valid_booking_ids).sum())

Valid booking IDs: 1000
Invalid booking IDs: 0

### Check Booking ID

In [ ]:
print("Duplicate booking IDs:", clean_bookings["booking_id"].duplicated().sum())

Duplicate booking IDs: 0

### Check Flight IDs

In [ ]:
valid_flight_refs = clean_bookings["flight_id"].isin(
    clean_flights["flight_id"]
)

print("Valid flight references:", valid_flight_refs.sum())
print("Invalid flight references:", (~valid_flight_refs).sum())

Valid flight references: 1000
Invalid flight references: 0

### Check Passenger IDs

In [ ]:
valid_passenger_refs = clean_bookings["passenger_id"].isin(
    passengers["passenger_id"]
)

print("Valid passenger references:", valid_passenger_refs.sum())
print("Invalid passenger references:", (~valid_passenger_refs).sum())

Valid passenger references: 1000
Invalid passenger references: 0

### Check Booking Date

In [ ]:
clean_bookings["booking_date"] = pd.to_datetime(
    clean_bookings["booking_date"],
    errors="coerce"
)

print("Missing booking dates:", clean_bookings["booking_date"].isnull().sum())
print("Earliest booking date:", clean_bookings["booking_date"].min())
print("Latest booking date:", clean_bookings["booking_date"].max())

Missing booking dates: 0
Earliest booking date: 2025-04-17 11:37:36.951000
Latest booking date: 2026-04-17 11:37:36.951000

### Check Date Order

In [ ]:
booking_flight_check = clean_bookings.merge(
    clean_flights[["flight_id", "departure_time"]],
    on="flight_id",
    how="left"
)

invalid_booking_dates = (
    booking_flight_check["booking_date"]
    > booking_flight_check["departure_time"]
)

print(
    "Bookings after flight departure:",
    invalid_booking_dates.sum()
)

Bookings after flight departure: 0

### Check Seat

In [ ]:
seat_pattern = r"^\d{1,2}[A-F]$"

valid_seats = clean_bookings["seat_number"].astype(str).str.match(
    seat_pattern
)

print("Valid seat numbers:", valid_seats.sum())
print("Invalid seat numbers:", (~valid_seats).sum())

Valid seat numbers: 1000
Invalid seat numbers: 0

### Identify PII

In [ ]:
pii_columns = [
    "passport_number",
    "emergency_contact_name",
    "emergency_contact_phone"
]

print("PII columns:")
print(pii_columns)

PII columns:
['passport_number', 'emergency_contact_name', 'emergency_contact_phone']

### Mask PII

In [ ]:
pii_safe_bookings = clean_bookings.copy()

pii_safe_bookings["passport_number"] = (
    pii_safe_bookings["passport_number"]
    .astype(str)
    .str[:2] + "****"
)

pii_safe_bookings["emergency_contact_name"] = "MASKED"

pii_safe_bookings["emergency_contact_phone"] = "MASKED"

print(pii_safe_bookings[pii_columns].head(10))

  passport_number emergency_contact_name emergency_contact_phone
0          P1****                 MASKED                  MASKED
1          L3****                 MASKED                  MASKED
2          G8****                 MASKED                  MASKED
3          M0****                 MASKED                  MASKED
4          N5****                 MASKED                  MASKED
5          B0****                 MASKED                  MASKED
6          W9****                 MASKED                  MASKED
7          C3****                 MASKED                  MASKED
8          J9****                 MASKED                  MASKED
9          Y3****                 MASKED                  MASKED

### Final Check

In [ ]:
print("Final Bookings shape:", clean_bookings.shape)

print("\nMissing values:")
print(clean_bookings.isnull().sum())

print("\nDuplicate rows:", clean_bookings.duplicated().sum())

Final Bookings shape: (1000, 9)

Missing values:
booking_id                 0
passenger_id               0
flight_id                  0
booking_date               0
status                     0
passport_number            0
seat_number                0
emergency_contact_name     0
emergency_contact_phone    0
dtype: int64

Duplicate rows: 0

### Save Bookings

In [ ]:
clean_bookings.to_csv(
    "/content/drive/MyDrive/clean_bookings_checkpoint.csv",
    index=False
)

pii_safe_bookings.to_csv(
    "/content/drive/MyDrive/pii_safe_bookings.csv",
    index=False
)

print("Bookings checkpoint saved successfully!")

Bookings checkpoint saved successfully!

EDA PASSENGERS  ## 3. Passengers

### Clean Copy

In [ ]:
clean_passengers = passengers.copy()

print("Original rows:", len(passengers))
print("Clean passenger rows:", len(clean_passengers))

Original rows: 1039
Clean passenger rows: 1039

### Initial Check

In [ ]:
print("Shape:", clean_passengers.shape)

print("\nColumns:")
print(clean_passengers.columns.tolist())

print("\nData types:")
print(clean_passengers.dtypes)

print("\nMissing values:")
print(clean_passengers.isnull().sum())

print("\nDuplicate rows:", clean_passengers.duplicated().sum())

Shape: (1039, 9)

Columns:
['passenger_id', 'first_name', 'last_name', 'age', 'gender', 'email', 'phone', 'aadhaar_id', 'date_of_birth']

Data types:
passenger_id             object
first_name               object
last_name                object
age                       int64
gender                   object
email                    object
phone                    object
aadhaar_id                int64
date_of_birth    datetime64[ns]
dtype: object

Missing values:
passenger_id      0
first_name        0
last_name        10
age               0
gender            0
email             0
phone             0
aadhaar_id        0
date_of_birth     0
dtype: int64

Duplicate rows: 0

### Validate ID

In [ ]:
passenger_id_pattern = r"^P\d{4}$"

valid_passenger_ids = clean_passengers["passenger_id"].astype(str).str.match(
    passenger_id_pattern
)

print("Valid passenger IDs:", valid_passenger_ids.sum())
print("Invalid passenger IDs:", (~valid_passenger_ids).sum())

Valid passenger IDs: 1039
Invalid passenger IDs: 0

### Check ID

In [ ]:
print(
    "Duplicate passenger IDs:",
    clean_passengers["passenger_id"].duplicated().sum()
)

Duplicate passenger IDs: 39

### Inspect Duplicates

In [ ]:
duplicate_passengers = clean_passengers[
    clean_passengers["passenger_id"].duplicated(keep=False)
].sort_values("passenger_id")

duplicate_passengers.head(20)

,passenger_id,first_name,last_name,age,gender,email,phone,aadhaar_id,date_of_birth
34,P1034,Ishaan,Iyer,62,M,ishaan.iyer@outlook.com,+91-8679984033,122362316658,1964-08-14
35,P1034,Ishaan,Iyer,62,M,ishaan.iyer@gmail.com,+91-7994310083,669096705466,1964-09-24
103,P1102,Myra,Kulkarni,1,F,myra.kulkarni@rediffmail.com,+91-8128636900,606853615305,2025-02-27
104,P1102,Myra,Kulkarni,1,F,myra.kulkarni@outlook.com,+91-7247746438,47277901043,2025-03-18
106,P1104,Vivaan,Verma,88,F,vivaan.verma@gmail.com,+91-7871531100,246095396218,1938-06-03
107,P1104,Vivaan,Verma,88,F,vivaan.verma@hotmail.com,+91-6519246503,706540515319,1938-12-25
108,P1104,Vivaan,Verma,88,F,vivaan.verma@outlook.com,+91-7147605080,585277221704,1938-04-02
113,P1108,IshaanKulkarni,NaN,8,M,ishaankulkarni.user@outlook.com,+91-8511086777,909275571928,2018-06-13
112,P1108,Ishaan,Kulkarni,8,M,ishaan.kulkarni@outlook.com,+91-9394801573,16582029702,2018-02-08
145,P1140,Shaurya,Singh,42,M,shaurya.singh@outlook.com,+91-6525146690,403910651801,1984-08-02
146,P1140,Shaurya,Singh,42,M,shaurya.singh1@outlook.com,+91-9293253475,265676618251,1984-03-18
147,P1141,Sai,Kulkarni,77,M,sai.kulkarni@rediffmail.com,+91-7881531720,300478686337,1949-06-05
148,P1141,SaiKulkarni,NaN,77,M,saikulkarni.user@outlook.com,+91-7878488534,106903311907,1949-10-22
185,P1178,Kavya,Naidu,72,M,kavya.naidu@outlook.com,+91-8682014641,78361340745,1954-02-15
186,P1178,Kavyanaidu,NaN,72,M,kavyanaidu.user@gmail.com,+91-7325354965,959629233095,1954-09-09
225,P1216,Riya,Sharma,56,F,riya.sharma@hotmail.com,+91-9208908082,793271040541,1970-02-11
224,P1216,Riya,Sharma,56,F,riya.sharma@outlook.com,+91-7367942460,154100676267,1970-07-12
246,P1236,MyraSharma,NaN,20,F,myrasharma.user@outlook.com,+91-6338642889,534655494717,2006-01-28
245,P1236,Myra,Sharma,20,F,myra.sharma@yahoo.com,+91-9821413281,584282417248,2006-03-22
262,P1252,Aadhya,Agarwal,16,M,aadhya.agarwal@rediffmail.com,+91-7987380851,890028772175,2010-04-11

### Count Duplicates

In [ ]:
duplicate_id_counts = (
    clean_passengers["passenger_id"]
    .value_counts()
)

duplicate_id_counts = duplicate_id_counts[
    duplicate_id_counts > 1
]

print("Duplicate passenger IDs:", len(duplicate_id_counts))
print("\nRecords involved:", duplicate_id_counts.sum())

Duplicate passenger IDs: 36

Records involved: 75

### Compare Duplicates

In [ ]:
duplicate_passengers[
    ["passenger_id", "first_name", "last_name", "age", "gender"]
].head(30)

    passenger_id      first_name last_name  age gender
34         P1034          Ishaan      Iyer   62      M
35         P1034          Ishaan      Iyer   62      M
103        P1102            Myra  Kulkarni    1      F
104        P1102            Myra  Kulkarni    1      F
106        P1104          Vivaan     Verma   88      F
107        P1104          Vivaan     Verma   88      F
108        P1104          Vivaan     Verma   88      F
113        P1108  IshaanKulkarni       NaN    8      M
112        P1108          Ishaan  Kulkarni    8      M
145        P1140         Shaurya     Singh   42      M
146        P1140         Shaurya     Singh   42      M
147        P1141             Sai  Kulkarni   77      M
148        P1141     SaiKulkarni       NaN   77      M
185        P1178           Kavya     Naidu   72      M
186        P1178      Kavyanaidu       NaN   72      M
225        P1216            Riya    Sharma   56      F
224        P1216            Riya    Sharma   56      F
246        P1236      MyraSharma       NaN   20      F
245        P1236            Myra    Sharma   20      F
262        P1252          Aadhya   Agarwal   16      M
263        P1252          Aadhya   Agarwal   16      M
342        P1331          Aadhya     Naidu   60      F
343        P1331          Aadhya     Naidu   60      F
420        P1408            Diya    Mishra   16      F
421        P1408            Diya    mishra   16      F
422        P1408            Diya    Mishra   16      F
428        P1413         Shaurya     Mehta   63      M
427        P1413         Shaurya     Mehta   63      M
484        P1469          Aadhya     Reddy   84      F
485        P1469          Aadhya     Reddy   84      F

### Check Names

In [ ]:
missing_last_names = clean_passengers[
    clean_passengers["last_name"].isnull()
]

print("Missing last names:", len(missing_last_names))

missing_last_names[
    ["passenger_id", "first_name", "last_name", "email"]
]

Missing last names: 10

     passenger_id      first_name last_name                            email
113         P1108  IshaanKulkarni       NaN  ishaankulkarni.user@outlook.com
148         P1141     SaiKulkarni       NaN     saikulkarni.user@outlook.com
186         P1178      Kavyanaidu       NaN        kavyanaidu.user@gmail.com
246         P1236      MyraSharma       NaN      myrasharma.user@outlook.com
805         P1781      ArjunSingh       NaN      arjunsingh.user@outlook.com
919         P1889    AadhyapPatel       NaN      aadhyappatel.user@yahoo.com
978         P1944       RiyaGupta       NaN         riyagupta.user@yahoo.com
1021        P1985      AadhyaNair       NaN        aadhyanair.user@gmail.com
1032        P1994    DiyaKulkarni       NaN      diyakulkarni.user@gmail.com
1038        P1999    AnanyaPillai       NaN    ananyapillai.user@outlook.com

### Fill Names

In [ ]:
clean_passengers["last_name"] = clean_passengers["last_name"].fillna(
    "UNKNOWN"
)

print(
    "Missing last names:",
    clean_passengers["last_name"].isnull().sum()
)

Missing last names: 0

### Check Age

In [ ]:
print("Minimum age:", clean_passengers["age"].min())
print("Maximum age:", clean_passengers["age"].max())

print(
    "Invalid ages:",
    ((clean_passengers["age"] < 0) |
     (clean_passengers["age"] > 120)).sum()
)

Minimum age: 1
Maximum age: 89
Invalid ages: 0

### Check Gender

In [ ]:
print(clean_passengers["gender"].value_counts(dropna=False))

gender
M    545
F    494
Name: count, dtype: int64

### Check Email

In [ ]:
email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

valid_emails = clean_passengers["email"].astype(str).str.match(
    email_pattern
)

print("Valid emails:", valid_emails.sum())
print("Invalid emails:", (~valid_emails).sum())

Valid emails: 1039
Invalid emails: 0

### Check Phone

In [ ]:
phone_pattern = r"^\+91-\d{10}$"

valid_phones = clean_passengers["phone"].astype(str).str.match(
    phone_pattern
)

print("Valid phone numbers:", valid_phones.sum())
print("Invalid phone numbers:", (~valid_phones).sum())

Valid phone numbers: 1039
Invalid phone numbers: 0

In [ ]:
### Check Aadhaar

In [ ]:
aadhaar_pattern = r"^\d{12}$"

valid_aadhaar = clean_passengers["aadhaar_id"].astype(str).str.match(
    aadhaar_pattern
)

print("Valid Aadhaar IDs:", valid_aadhaar.sum())
print("Invalid Aadhaar IDs:", (~valid_aadhaar).sum())

Valid Aadhaar IDs: 925
Invalid Aadhaar IDs: 114

### Inspect Aadhaar

In [ ]:
invalid_aadhaar_rows = clean_passengers[
    ~valid_aadhaar
]

invalid_aadhaar_rows[
    ["passenger_id", "aadhaar_id"]
].head(20)

    passenger_id   aadhaar_id
5          P1005  56413953767
12         P1012  31051834738
43         P1042  75273545494
51         P1050  67974034471
57         P1056  34824771093
76         P1075  20539502402
78         P1077   7661771159
89         P1088  60715969664
104        P1102  47277901043
112        P1108  16582029702
121        P1116  78447364710
125        P1120  47974801624
137        P1132  26206724004
149        P1142  67383028439
158        P1151  62312038750
168        P1161  46618398262
176        P1169  71461125457
184        P1177  43842797881
185        P1178  78361340745
196        P1188  43898364037

### Fix Aadhaar

In [ ]:
clean_passengers.loc[
    ~valid_aadhaar,
    "aadhaar_id"
] = "UNKNOWN"

print(
    "Invalid Aadhaar IDs:",
    (clean_passengers["aadhaar_id"] == "UNKNOWN").sum()
)

Invalid Aadhaar IDs: 114

/tmp/ipykernel_2780/2249628140.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'UNKNOWN' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  clean_passengers.loc[

### Fix Aadhaar

In [ ]:
clean_passengers["aadhaar_id"] = clean_passengers["aadhaar_id"].astype(str)

clean_passengers.loc[
    ~valid_aadhaar,
    "aadhaar_id"
] = "UNKNOWN"

print(
    "Unknown Aadhaar IDs:",
    (clean_passengers["aadhaar_id"] == "UNKNOWN").sum()
)

Unknown Aadhaar IDs: 114

### Check DOB

In [ ]:
clean_passengers["date_of_birth"] = pd.to_datetime(
    clean_passengers["date_of_birth"],
    errors="coerce"
)

print("Missing DOB:", clean_passengers["date_of_birth"].isnull().sum())
print("Earliest DOB:", clean_passengers["date_of_birth"].min())
print("Latest DOB:", clean_passengers["date_of_birth"].max())

Missing DOB: 0
Earliest DOB: 1937-01-11 00:00:00
Latest DOB: 2025-12-15 00:00:00

### Check Age DOB

In [ ]:
reference_date = pd.Timestamp("2026-04-20")

calculated_age = (
    reference_date.year
    - clean_passengers["date_of_birth"].dt.year
)

birthday_passed = (
    (clean_passengers["date_of_birth"].dt.month < reference_date.month)
    |
    (
        (clean_passengers["date_of_birth"].dt.month == reference_date.month)
        &
        (clean_passengers["date_of_birth"].dt.day <= reference_date.day)
    )
)

calculated_age = calculated_age - (~birthday_passed)

age_difference = calculated_age - clean_passengers["age"]

print("Age mismatches:", (age_difference != 0).sum())

Age mismatches: 721

### Inspect Age

In [ ]:
age_check = clean_passengers.copy()

age_check["calculated_age"] = calculated_age
age_check["age_difference"] = age_difference

age_check[
    age_check["age_difference"] != 0
][
    ["passenger_id", "age", "date_of_birth",
     "calculated_age", "age_difference"]
].head(20)

   passenger_id  age date_of_birth  calculated_age  age_difference
2         P1002   72    1954-09-10              71              -1
4         P1004   21    2005-11-11              20              -1
7         P1007   75    1951-11-24              74              -1
8         P1008   75    1951-11-10              74              -1
14        P1014    2    2024-09-04               1              -1
15        P1015   88    1938-05-26              87              -1
17        P1017   38    1988-10-02              37              -1
18        P1018    2    2024-08-11               1              -1
19        P1019   64    1962-06-10              63              -1
20        P1020   60    1966-12-18              59              -1
22        P1022   33    1993-06-19              32              -1
23        P1023   76    1950-10-24              75              -1
24        P1024   58    1968-08-08              57              -1
25        P1025   22    2004-07-22              21              -1
26        P1026   89    1937-10-17              88              -1
27        P1027   49    1977-10-11              48              -1
28        P1028   59    1967-10-10              58              -1
29        P1029   42    1984-12-06              41              -1
30        P1030   60    1966-10-28              59              -1
31        P1031   80    1946-12-17              79              -1

### Check Age Difference

In [ ]:
print(
    age_difference.value_counts().sort_index()
)

-1    721
 0    318
Name: count, dtype: int64

### Check Names

In [ ]:
print("Missing first names:", clean_passengers["first_name"].isnull().sum())
print("Missing last names:", clean_passengers["last_name"].isnull().sum())

print("\nSample names:")
print(clean_passengers[["first_name", "last_name"]].head(10))

Missing first names: 0
Missing last names: 0

Sample names:
  first_name   last_name
0     Vivaan  Chatterjee
1    Krishna       Reddy
2       Myra       Naidu
3       Myra      Mishra
4     Saanvi    Banerjee
5    Reyansh       Joshi
6      Kavya        Nair
7       Sara       Joshi
8      Kavya      Pillai
9        Sai    Kulkarni

### Keep Unique IDs

In [ ]:
clean_passengers = clean_passengers.drop_duplicates(
    subset="passenger_id",
    keep="first"
)

print("Final passenger rows:", len(clean_passengers))
print(
    "Duplicate passenger IDs:",
    clean_passengers["passenger_id"].duplicated().sum()
)

Final passenger rows: 1000
Duplicate passenger IDs: 0

### Final Check

In [ ]:
print("Final Passengers shape:", clean_passengers.shape)

print("\nMissing values:")
print(clean_passengers.isnull().sum())

print("\nDuplicate rows:", clean_passengers.duplicated().sum())

print(
    "Duplicate passenger IDs:",
    clean_passengers["passenger_id"].duplicated().sum()
)

Final Passengers shape: (1000, 9)

Missing values:
passenger_id     0
first_name       0
last_name        0
age              0
gender           0
email            0
phone            0
aadhaar_id       0
date_of_birth    0
dtype: int64

Duplicate rows: 0
Duplicate passenger IDs: 0

### Mask PII

In [ ]:
pii_safe_passengers = clean_passengers.copy()

pii_safe_passengers["email"] = "MASKED"
pii_safe_passengers["phone"] = "MASKED"
pii_safe_passengers["aadhaar_id"] = "MASKED"

print(
    pii_safe_passengers[
        ["email", "phone", "aadhaar_id"]
    ].head(10)
)

    email   phone aadhaar_id
0  MASKED  MASKED     MASKED
1  MASKED  MASKED     MASKED
2  MASKED  MASKED     MASKED
3  MASKED  MASKED     MASKED
4  MASKED  MASKED     MASKED
5  MASKED  MASKED     MASKED
6  MASKED  MASKED     MASKED
7  MASKED  MASKED     MASKED
8  MASKED  MASKED     MASKED
9  MASKED  MASKED     MASKED

### Save Data

In [ ]:
clean_passengers.to_csv(
    "/content/drive/MyDrive/clean_passengers_checkpoint.csv",
    index=False
)

pii_safe_passengers.to_csv(
    "/content/drive/MyDrive/pii_safe_passengers.csv",
    index=False
)

print("Passenger files saved successfully.")

Passenger files saved successfully.

**PAYMENT**

### Payment Copy

In [ ]:
clean_payments = payments.copy()

print("Payments shape:", clean_payments.shape)
print("\nMissing values:")
print(clean_payments.isnull().sum())

Payments shape: (1000, 4)

Missing values:
payment_id         0
booking_id         0
amount            48
payment_method     0
dtype: int64

### Check Duplicates

In [ ]:
print("Duplicate rows:", clean_payments.duplicated().sum())

print(
    "Duplicate payment IDs:",
    clean_payments["payment_id"].duplicated().sum()
)

Duplicate rows: 0
Duplicate payment IDs: 0

### Check Payment ID

In [ ]:
payment_id_pattern = r"^PAY\d{4}$"

valid_payment_ids = (
    clean_payments["payment_id"]
    .astype(str)
    .str.match(payment_id_pattern)
)

print("Valid payment IDs:", valid_payment_ids.sum())
print("Invalid payment IDs:", (~valid_payment_ids).sum())

Valid payment IDs: 1000
Invalid payment IDs: 0

### Check Booking IDs

In [ ]:
valid_booking_refs = clean_payments["booking_id"].isin(
    clean_bookings["booking_id"]
)

print("Valid booking references:", valid_booking_refs.sum())
print("Invalid booking references:", (~valid_booking_refs).sum())

Valid booking references: 1000
Invalid booking references: 0

### Check Amount

In [ ]:
print("Missing amounts:", clean_payments["amount"].isnull().sum())

print("\nAmount summary:")
print(clean_payments["amount"].describe())

Missing amounts: 48

Amount summary:
count         952
unique        922
top       INVALID
freq           30
Name: amount, dtype: object

In [ ]:
### Check Invalid

In [ ]:
print(
    "Invalid amounts:",
    (clean_payments["amount"] == "INVALID").sum()
)

print(
    "Missing amounts:",
    clean_payments["amount"].isnull().sum()
)

Invalid amounts: 30
Missing amounts: 48

### Clean Amount

In [ ]:
clean_payments["amount"] = pd.to_numeric(
    clean_payments["amount"],
    errors="coerce"
)

print("Missing amounts after cleaning:", clean_payments["amount"].isnull().sum())

Missing amounts after cleaning: 78

### Check Amounts

In [ ]:
invalid_amounts = clean_payments["amount"].notna() & (
    clean_payments["amount"] <= 0
)

print("Non-positive amounts:", invalid_amounts.sum())

print("\nMinimum amount:", clean_payments["amount"].min())
print("Maximum amount:", clean_payments["amount"].max())

Non-positive amounts: 0

Minimum amount: 1002.59
Maximum amount: 14992.95

### Check Methods

In [ ]:
print(clean_payments["payment_method"].value_counts(dropna=False))

payment_method
UPI           358
CARD          329
NETBANKING    313
Name: count, dtype: int64

### Final Check

In [ ]:
print("Final Payments shape:", clean_payments.shape)

print("\nMissing values:")
print(clean_payments.isnull().sum())

print("\nDuplicate rows:", clean_payments.duplicated().sum())

print(
    "Duplicate payment IDs:",
    clean_payments["payment_id"].duplicated().sum()
)

Final Payments shape: (1000, 4)

Missing values:
payment_id         0
booking_id         0
amount            78
payment_method     0
dtype: int64

Duplicate rows: 0
Duplicate payment IDs: 0

### Save Data

In [ ]:
clean_payments.to_csv(
    "/content/drive/MyDrive/clean_payments_checkpoint.csv",
    index=False
)

print("Payment file saved successfully.")

Payment file saved successfully.

###DATA MODELINGJoin Flights

In [ ]:
booking_flights = clean_bookings.merge(
    clean_flights,
    on="flight_id",
    how="left",
    suffixes=("_booking", "_flight")
)

print("Booking-Flight shape:", booking_flights.shape)

print(
    "Missing flight matches:",
    booking_flights["airline"].isnull().sum()
)

Booking-Flight shape: (1002, 20)
Missing flight matches: 0

Check Flight IDs

In [ ]:
print("Flight rows:", len(clean_flights))
print(
    "Unique flight IDs:",
    clean_flights["flight_id"].nunique()
)

print(
    "Duplicate flight IDs:",
    clean_flights["flight_id"].duplicated().sum()
)

Flight rows: 1005
Unique flight IDs: 1004
Duplicate flight IDs: 1

### Find Duplicate

In [ ]:
duplicate_flights = clean_flights[
    clean_flights["flight_id"].duplicated(keep=False)
]

print(duplicate_flights)

    flight_id airline source destination          departure_time  \
253     6F250  IndiGo    DEL         BLR 2026-04-20 03:26:41.701
270     6F250  IndiGo    CCU         BLR 2026-04-20 02:23:41.702

               arrival_time  duration  duration_minutes  is_overnight  \
253 2026-04-20 07:30:41.701  04:04:00             244.0         False
270 2026-04-20 02:56:41.702  00:33:00              33.0         False

    departure_date  departure_hour      route
253     2026-04-20               3  DEL → BLR
270     2026-04-20               2  CCU → BLR

### Check Flight

In [ ]:
bookings_6f250 = clean_bookings[
    clean_bookings["flight_id"] == "6F250"
]

print(bookings_6f250)
print("\nNumber of bookings:", len(bookings_6f250))

    booking_id passenger_id flight_id            booking_date     status  \
235      B1235        P1979     6F250 2025-12-23 11:37:36.951    PENDING
294      B1294        P1898     6F250 2025-07-13 11:37:36.951  CANCELLED

    passport_number seat_number emergency_contact_name emergency_contact_phone
235        Y7698731         13D          Vedhika Khare          +91-9835680345
294        J2383972         34B            Hitesh Sant          +91-7709899502

Number of bookings: 2

### Record Issue

In [ ]:
duplicate_flight_ids = (
    clean_flights["flight_id"]
    [clean_flights["flight_id"].duplicated(keep=False)]
    .unique()
)

print("Duplicate flight IDs:", duplicate_flight_ids)
print("Count:", len(duplicate_flight_ids))

Duplicate flight IDs: ['6F250']
Count: 1

### Add Flight Key

In [ ]:
clean_flights["flight_key"] = range(1, len(clean_flights) + 1)

print(
    clean_flights[
        ["flight_key", "flight_id", "source", "destination"]
    ][clean_flights["flight_id"] == "6F250"]
)

     flight_key flight_id source destination
253         251     6F250    DEL         BLR
270         268     6F250    CCU         BLR

In [ ]:
clean_flights.to_csv(
    "/content/drive/MyDrive/clean_flights_checkpoint.csv",
    index=False
)

print("Updated Flights checkpoint saved.")

Updated Flights checkpoint saved.

### Prepare Flights

In [ ]:
flights_for_join = clean_flights.drop_duplicates(
    subset="flight_id",
    keep="first"
)

print("Flights for join:", len(flights_for_join))
print(
    "Duplicate IDs:",
    flights_for_join["flight_id"].duplicated().sum()
)

Flights for join: 1004
Duplicate IDs: 0

Bookings.flight_id
        │
        ▼
Flights.flight_id

In [ ]:
booking_flights = clean_bookings.merge(
    clean_flights.drop_duplicates(
        subset="flight_id",
        keep="first"
    ),
    on="flight_id",
    how="left",
    suffixes=("_booking", "_flight")
)

print("Booking-Flight rows:", len(booking_flights))
print(
    "Missing flight matches:",
    booking_flights["airline"].isnull().sum()
)

Booking-Flight rows: 1000
Missing flight matches: 0

In [ ]:
clean_flights.drop_duplicates(subset="flight_id", keep="first")

,flight_id,airline,source,destination,departure_time,arrival_time,duration,duration_minutes,is_overnight,departure_date,departure_hour,route,flight_key
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00,174.0,True,2026-04-20,23,CCU → MAA,1
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00,108.0,True,2026-04-20,23,BOM → CCU,2
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00,105.0,True,2026-04-20,23,BOM → CCU,3
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00,156.0,True,2026-04-20,23,BOM → CCU,4
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00,299.0,True,2026-04-20,23,MAA → BOM,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,6F198,IndiGo,HYD,BLR,2026-04-17 12:40:41.703,2026-04-17 17:39:41.703,04:59:00,299.0,False,2026-04-17,12,HYD → BLR,1001
1016,AI093,Air India,BOM,BLR,2026-04-17 12:35:41.702,2026-04-17 17:28:41.702,04:53:00,293.0,False,2026-04-17,12,BOM → BLR,1002
1017,UK062,Vistara,HYD,DEL,2026-04-17 12:33:41.701,2026-04-17 15:35:41.701,03:02:00,182.0,False,2026-04-17,12,HYD → DEL,1003
1018,6F057,IndiGo,MAA,DEL,2026-04-17 12:32:41.701,2026-04-17 15:50:41.701,03:18:00,198.0,False,2026-04-17,12,MAA → DEL,1004
1019,UK064,Vistara,BOM,DEL,2026-04-17 12:25:41.701,2026-04-17 14:55:41.701,02:30:00,150.0,False,2026-04-17,12,BOM → DEL,1005

Check Passengers

In [ ]:
booking_passengers = clean_bookings.merge(
    clean_passengers,
    on="passenger_id",
    how="left",
    suffixes=("_booking", "_passenger")
)

print("Booking-Passenger rows:", len(booking_passengers))
print(
    "Missing passenger matches:",
    booking_passengers["first_name"].isnull().sum()
)

Booking-Passenger rows: 1000
Missing passenger matches: 0

### Join Payments

In [ ]:
booking_payments = clean_bookings.merge(
    clean_payments,
    on="booking_id",
    how="left",
    suffixes=("_booking", "_payment")
)

print("Booking-Payment rows:", len(booking_payments))
print(
    "Missing payment matches:",
    booking_payments["payment_id"].isnull().sum()
)

Booking-Payment rows: 1363
Missing payment matches: 363

### Check Booking IDs

In [ ]:
payment_booking_counts = clean_payments["booking_id"].value_counts()

duplicate_payment_bookings = payment_booking_counts[
    payment_booking_counts > 1
]

print("Booking IDs with multiple payments:",
      len(duplicate_payment_bookings))

print("\nPayment records involved:",
      duplicate_payment_bookings.sum())

print("\nSample:")
print(duplicate_payment_bookings.head(10))

Booking IDs with multiple payments: 267

Payment records involved: 630

Sample:
booking_id
B1663    6
B1895    5
B1165    4
B1652    4
B1699    4
B1272    4
B1359    4
B1761    4
B1623    4
B1939    4
Name: count, dtype: int64

### Missing Payments

In [ ]:
payment_booking_ids = set(clean_payments["booking_id"])

missing_payment_bookings = clean_bookings[
    ~clean_bookings["booking_id"].isin(payment_booking_ids)
]

print("Bookings without payment:", len(missing_payment_bookings))

print("\nSample:")
print(
    missing_payment_bookings[
        ["booking_id", "passenger_id", "flight_id", "status"]
    ].head(10)
)

Bookings without payment: 363

Sample:
   booking_id passenger_id flight_id     status
0       B1000        P1591     AI192  CANCELLED
1       B1001        P1803     6F026  CANCELLED
3       B1003        P1364     AI069  CONFIRMED
7       B1007        P1838     UK167  CONFIRMED
8       B1008        P1406     AI245    PENDING
9       B1009        P1424     SJ158  CANCELLED
14      B1014        P1411     SJ172    PENDING
17      B1017        P1158     UK067  CONFIRMED
22      B1022        P1072     AI080  CONFIRMED
28      B1028        P1601     SJ239  CANCELLED

KPI preparation   ### Booking Table

In [ ]:
booking_analysis = booking_flights.copy()

print("Rows:", len(booking_analysis))
print("\nColumns:")
print(booking_analysis.columns.tolist())

Rows: 1000

Columns:
['booking_id', 'passenger_id', 'flight_id', 'booking_date', 'status', 'passport_number', 'seat_number', 'emergency_contact_name', 'emergency_contact_phone', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration', 'duration_minutes', 'is_overnight', 'departure_date', 'departure_hour', 'route', 'flight_key']

### Add KPI Fields

In [ ]:
booking_analysis["is_confirmed"] = (
    booking_analysis["status"] == "CONFIRMED"
)

booking_analysis["is_cancelled"] = (
    booking_analysis["status"] == "CANCELLED"
)

booking_analysis["is_pending"] = (
    booking_analysis["status"] == "PENDING"
)

print(
    booking_analysis[
        ["booking_id", "status",
         "is_confirmed", "is_cancelled", "is_pending"]
    ].head(10)
)

  booking_id     status  is_confirmed  is_cancelled  is_pending
0      B1000  CANCELLED         False          True       False
1      B1001  CANCELLED         False          True       False
2      B1002  CANCELLED         False          True       False
3      B1003  CONFIRMED          True         False       False
4      B1004    PENDING         False         False        True
5      B1005  CONFIRMED          True         False       False
6      B1006  CANCELLED         False          True       False
7      B1007  CONFIRMED          True         False       False
8      B1008    PENDING         False         False        True
9      B1009  CANCELLED         False          True       False

### Status Summary

In [ ]:
print("Confirmed:", booking_analysis["is_confirmed"].sum())
print("Cancelled:", booking_analysis["is_cancelled"].sum())
print("Pending:", booking_analysis["is_pending"].sum())
print(
    "Unknown:",
    (booking_analysis["status"] == "UNKNOWN").sum()
)

Confirmed: 320
Cancelled: 314
Pending: 291
Unknown: 75

### Booking Rates

In [ ]:
total_bookings = len(booking_analysis)

confirmation_rate = (
    booking_analysis["is_confirmed"].sum()
    / total_bookings
) * 100

cancellation_rate = (
    booking_analysis["is_cancelled"].sum()
    / total_bookings
) * 100

print("Confirmation rate:", round(confirmation_rate, 2), "%")
print("Cancellation rate:", round(cancellation_rate, 2), "%")

Confirmation rate: 32.0 %
Cancellation rate: 31.4 %

### Flight Summary

In [ ]:
print("Total flights:", len(clean_flights))

print("\nFlights by airline:")
print(clean_flights["airline"].value_counts())

print("\nOvernight flights:",
      clean_flights["is_overnight"].sum())

print("\nAverage duration:",
      round(clean_flights["duration_minutes"].mean(), 2),
      "minutes")

Total flights: 1005

Flights by airline:
airline
IndiGo       273
Air India    255
SpiceJet     247
Vistara      230
Name: count, dtype: int64

Overnight flights: 122

Average duration: 164.62 minutes

In [ ]:
route_counts = clean_flights["route"].value_counts()

print("Top 10 routes:")
print(route_counts.head(10))

Top 10 routes:
route
BOM → CCU    90
CCU → DEL    72
MAA → BLR    65
BLR → BOM    60
HYD → MAA    57
DEL → HYD    54
HYD → DEL    42
BOM → DEL    39
CCU → BOM    33
DEL → BLR    29
Name: count, dtype: int64

### Payment KPIs

In [ ]:
valid_payments = clean_payments["amount"].notna()

total_revenue = clean_payments.loc[
    valid_payments, "amount"
].sum()

average_payment = clean_payments.loc[
    valid_payments, "amount"
].mean()

print("Known payment revenue:", round(total_revenue, 2))
print("Average payment:", round(average_payment, 2))
print("Payments with known amount:", valid_payments.sum())
print("Payments with unknown amount:", (~valid_payments).sum())

Known payment revenue: 7385142.98
Average payment: 8009.92
Payments with known amount: 922
Payments with unknown amount: 78

### Payment Methods

In [ ]:
payment_method_counts = (
    clean_payments["payment_method"]
    .value_counts()
)

print(payment_method_counts)

payment_method
UPI           358
CARD          329
NETBANKING    313
Name: count, dtype: int64

### Save Tables

In [ ]:
booking_analysis.to_csv(
    "/content/drive/MyDrive/booking_analysis.csv",
    index=False
)

print("Booking analysis saved.")

Booking analysis saved.

### Payment Summary

In [ ]:
payment_summary = (
    clean_payments
    .groupby("booking_id", as_index=False)
    .agg(
        payment_count=("payment_id", "count"),
        total_payment=("amount", "sum")
    )
)

print("Payment summary rows:", len(payment_summary))
print("\nSample:")
print(payment_summary.head(10))

Payment summary rows: 637

Sample:
  booking_id  payment_count  total_payment
0      B1002              2        8593.08
1      B1004              1       12222.48
2      B1005              1       13378.90
3      B1006              1       14980.37
4      B1010              1           0.00
5      B1011              1        2115.18
6      B1012              4       23702.39
7      B1013              1        1176.33
8      B1015              2       19609.66
9      B1016              2       23800.77

### Fix Payment Sum

In [ ]:
payment_summary = (
    clean_payments
    .groupby("booking_id", as_index=False)
    .agg(
        payment_count=("payment_id", "count"),
        total_payment=("amount", "sum")
    )
)

amount_known = (
    clean_payments
    .groupby("booking_id")["amount"]
    .apply(lambda x: x.notna().any())
    .reset_index(name="amount_known")
)

payment_summary = payment_summary.merge(
    amount_known,
    on="booking_id",
    how="left"
)

payment_summary.loc[
    ~payment_summary["amount_known"],
    "total_payment"
] = pd.NA

print(payment_summary.head(10))

  booking_id  payment_count  total_payment  amount_known
0      B1002              2        8593.08          True
1      B1004              1       12222.48          True
2      B1005              1       13378.90          True
3      B1006              1       14980.37          True
4      B1010              1            NaN         False
5      B1011              1        2115.18          True
6      B1012              4       23702.39          True
7      B1013              1        1176.33          True
8      B1015              2       19609.66          True
9      B1016              2       23800.77          True

### Add Payments

In [ ]:
booking_analysis = booking_analysis.merge(
    payment_summary,
    on="booking_id",
    how="left"
)

print("Rows:", len(booking_analysis))
print(
    "Bookings with payment:",
    booking_analysis["payment_count"].notna().sum()
)

print(
    "Bookings without payment:",
    booking_analysis["payment_count"].isna().sum()
)

Rows: 1000
Bookings with payment: 637
Bookings without payment: 363

### Final Check

In [ ]:
print("Shape:", booking_analysis.shape)

print("\nMissing values:")
print(
    booking_analysis[
        ["booking_id", "passenger_id", "flight_id",
         "airline", "status", "payment_count",
         "total_payment"]
    ].isnull().sum()
)

print("\nDuplicate booking IDs:",
      booking_analysis["booking_id"].duplicated().sum())

Shape: (1000, 27)

Missing values:
booking_id         0
passenger_id       0
flight_id          0
airline            0
status             0
payment_count    363
total_payment    394
dtype: int64

Duplicate booking IDs: 0

### Save Analysis

In [ ]:
booking_analysis.to_csv(
    "/content/drive/MyDrive/booking_analysis.csv",
    index=False
)

print("Final analytical dataset saved.")

Final analytical dataset saved.

### Protect Analysis

In [ ]:
pii_safe_booking_analysis = booking_analysis.copy()

pii_columns = [
    "passport_number",
    "emergency_contact_name",
    "emergency_contact_phone"
]

pii_safe_booking_analysis = pii_safe_booking_analysis.drop(
    columns=pii_columns
)

print("Rows:", len(pii_safe_booking_analysis))
print("Columns:", len(pii_safe_booking_analysis.columns))

Rows: 1000
Columns: 24

### Save Safe Data

In [ ]:
pii_safe_booking_analysis.to_csv(
    "/content/drive/MyDrive/pii_safe_booking_analysis.csv",
    index=False
)

print("PII-safe analysis saved.")

PII-safe analysis saved.